### ISSUE TITLE
expose enum variant at runtime

### ISSUE THREAD

**Issue by vantessel** [dao-xyz/borsh-ts#17]
I have an `enum` for which I need to get the specific variant at runtime. I added a static field to the classes with the identifier but noted it was missing after deserialization, which from the test below I guess is the expected behaviour?

https://github.com/dao-xyz/borsh-ts/blob/a91fa5ef947d9ca71d0b8ba2d87e15f9b9ffbf30/src/__tests__/index.test.ts#L152-L169

Using the enum variant would work too, however I don't see an easy way to access it without looking into the bytes manually. Is there a workaround for this or any way I can access the variant at runtime?

**Comment by marcus-pousette** [comment]
Try 

import { getDiscriminator } from '@dao-xyz/borsh'

 it will yield all discriminator bytes before the class

**Comment by marcus-pousette** [comment]
static fields are not analyzed, so that is expected behaviour

**Comment by vantessel** [comment]
that worked, thank you!
